// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'main.dart';

List<RouteEntity> get routes => [
  RouteEntity(key: 'about', uri: Uri.parse('about'), routeBuilder: b0Builder),
  RouteEntity(
    key: 'lib/app',
    uri: Uri.parse('lib/app'),
    routeBuilder: b1Builder,
  ),
  RouteEntity(
    key: 'auth/login',
    uri: Uri.parse('auth/login'),
    routeBuilder: b2Builder,
  ),
  RouteEntity(
    key: 'notfound',
    uri: Uri.parse('notfound'),
    routeBuilder: b3Builder,
  ),
  RouteEntity(
    key: 'student/register',
    parent: 'student',
    uri: Uri.parse('student/register'),
    routeBuilder: b4Builder,
  ),
  RouteEntity(
    key: 'student/room',
    parent: 'student',
    uri: Uri.parse('student/room'),
    routeBuilder: b5Builder,
  ),
  RouteEntity(
    key: 'student',
    uri: Uri.parse('student'),
    routeBuilder: b6Builder,
  ),
  RouteEntity(
    key: 'type/list',
    uri: Uri.parse('type/list'),
    routeBuilder: b7Builder,
  ),
  RouteEntity(
    key: 'type/[id]',
    uri: Uri.parse('type/[id]'),
    routeBuilder: b8Builder,
  ),
];

const routePaths = (
  path: '/',
  about: '/about',
  lib: (path: '/lib', app: '/lib/app'),
  auth: (path: '/auth', login: '/auth/login'),
  notfound: '/notfound',
  student: (
    path: '/student',
    register: '/student/register',
    room: '/student/room',
  ),
  type: (path: '/type', list: '/type/list', $id: '/type/[id]'),
);
